[build-system]
requires = ["setuptools>=43", "wheel", "setuptools_scm", "cython~=0.29.20"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
target-version = ["py37"]

[tool.mypy]
warn_unused_configs = true

[[tool.mypy.overrides]]
module = [
    "pyfaidx",
    "matplotlib.*",
    "pylab",
    "scipy.stats",
    "networkx",
]
ignore_missing_imports = true
